baseURL = 'https://mandelliant.github.io/'
languageCode = 'en-us'
title = 'Mandelliant'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowWordCount = true
  ShowFullTextinRSS = true
  ShowToc = true
  TocOpen = false
  ShowPageNums = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    url = "/writing/"
    weight = 30
  [[menu.main]]
    identifier = "technology"
    name = "Technology"
    url = "/technology/"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"] 